### ISSUE TITLE
Build error 0.1.25-SNAPSHOT webcrawler connector

### ISSUE THREAD

**Issue by ajaytiwa** [MuleSoft-AI-Chain-Project/mule-web-crawler-connector#10]
I am trying to build " 0.1.25-SNAPSHOT" webcrawler connector from master branch 

I commented line 102 , 137 and 138 but getting below error.. anyone faced similar issue, 

using java 11 for the build

Execution default-test of goal com.mulesoft.munit:munit-extensions-maven-plugin:1.1.1:test failed: Plugin com.mulesoft.munit:munit-extensions-maven-plugin:1.1.1 or one of its dependencies could not be resolved: Could not transfer artifact com.mulesoft.munit:munit-remote:jar:jar-with-dependencies:2.3.2 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [mulesoft-plugin-releases (http://repository.mulesoft.org/releases/, default, releases+snapshots), mulesoft-plugin-snapshots (http://repository.mulesoft.org/snapshots/, default, releases+snapshots), mule-releases (http://repository.mulesoft.org/releases/, default, releases+snapshots)]

**Comment by tbolis-at-mulesoft** [comment]
Master can be now built without errors and dependency is also available on maven central 

```
<dependency>
   <groupId>io.github.mulesoft-ai-chain-project</groupId>
   <artifactId>mule4-webcrawler-connector</artifactId>
   <version>0.1.25</version>
   <classifier>mule-plugin</classifier>
</dependency>
```
