### ISSUE TITLE
JDK 8 Support

### ISSUE THREAD

**Issue by tbolis-at-mulesoft** [MuleSoft-AI-Chain-Project/mule-web-crawler-connector#16]
Bring back support for JDK 8

**Comment by tbolis-at-mulesoft** [comment]
Unfortunately Selenium discontinued support for JDK 1.8.

https://www.selenium.dev/blog/2023/java-8-support/

On September 30, 2023, Java 11 will be the minimum version supported by Selenium.

**Comment by amirkhan-ak-sf** [comment]
Than that's the tech limitation we have. We can close this issue and continue with J11 as minimum supported version.
