### ISSUE TITLE
Enable mac-web-crawler to Wait for Full Page Load Before Scanning

### ISSUE THREAD

**Issue by Ashwinsingh0951** [MuleSoft-AI-Chain-Project/mule-web-crawler-connector#4]
While testing the mac-web-crawler connector, I observed that it only scans the static page without waiting for it to fully load. Is there a way to configure the crawler to wait for the page to load before scanning?

**Comment by amirkhan-ak-sf** [comment]
@codedbyyogesh @alick888 FYA

**Comment by amirkhan-ak-sf** [comment]
@Ashwinsingh0951 The team has implemented it. Please use the develop branch to test it out.
